export default function Page() {
  return (
    <div className="container mx-auto">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>

      <p>
        Thank you for using ThinkAI! We are committed to protecting your privacy
        and providing a safe and secure experience. This Privacy Policy explains
        how we collect, use, store, and protect the data we collect from users
        of our application, particularly in relation to email addresses, profile
        images, and the AI responses provided.
      </p>

      <h2 className="text-xl font-bold mt-6 mb-3">Information We Collect</h2>

      <p>When you use ThinkAI, we may collect the following information:</p>

      <ul className="list-disc pl-6">
        <li>
          <strong>Email Addresses:</strong> If you choose to provide your email
          address, we may collect and store it. This enables us to deliver
          important updates and communications related to ThinkAI.
        </li>

        <li>
          <strong>Profile Images:</strong> If you choose to upload or associate
          a profile image with your account, we may collect and store it. This
          image is solely used for personalization within the app and to enhance
          user engagement.
        </li>

        <li>
          <strong>AI-Generated Responses:</strong> Please note that ThinkAI
          utilizes AI algorithms to generate responses to user queries. While we
          strive to provide accurate and helpful information, the app&apos;s
          responses should be interpreted as generated by algorithms and not
          verified by human moderators.
        </li>
      </ul>

      <h2 className="text-xl font-bold mt-6 mb-3">Third-Party Integrations</h2>

      <p>
        ThinkAI may integrate with third-party services for collecting email
        addresses or profile images. These services are governed by their own
        privacy policies, and we encourage you to review those policies to
        understand how your data will be handled.
      </p>

      <h2 className="text-xl font-bold mt-6 mb-3">Children&apos;s Privacy</h2>

      <p>
        ThinkAI is not intended for users under the age of 13. We do not
        knowingly collect personal information from users in this age group. If
        you are a parent or guardian and believe your child may have provided
        personal information, please contact us immediately, and we will take
        steps to promptly delete the information.
      </p>

      <h2 className="text-xl font-bold mt-6 mb-3">
        Use of Collected Information
      </h2>

      <p>We utilize the collected information in the following ways:</p>

      <ul className="list-disc pl-6">
        <li>
          <strong>Email Communication:</strong> If you provide your email
          address, we may use it to send important announcements, updates, and
          notifications related to ThinkAI. You can manage your email
          preferences within the app settings.
        </li>

        <li>
          <strong>Personalization:</strong> Your profile image, if provided, may
          be used to personalize your experience within ThinkAI, such as
          displaying it within the app.
        </li>
      </ul>

      <h2 className="text-xl font-bold mt-6 mb-3">Data Security</h2>

      <p>
        We prioritize the security of your data and have implemented
        industry-standard measures to protect it from unauthorized access or
        disclosure. However, please keep in mind that no method of data
        transmission over the internet or electronic storage is 100% secure.
        While we strive to use commercially acceptable means to protect your
        personal information, we cannot guarantee its absolute security.
      </p>

      <h2 className="text-xl font-bold mt-6 mb-3">
        Changes to this Privacy Policy
      </h2>

      <p>
        We reserve the right to update or change this Privacy Policy at any
        time. Any modifications will be effective immediately upon posting the
        updated policy within the ThinkAI application. We encourage you to
        review this Privacy Policy periodically for any updates or changes.
      </p>

      <h2 className="text-xl font-bold mt-6 mb-3">Contact Us</h2>

      <p>
        If you have any questions, concerns, or requests regarding this Privacy
        Policy or our data practices, please contact us at:
      </p>

      <ul className="list-disc pl-6">
        <li>
          <strong>Email:</strong> mustafa.wael.dev@gmail.com
        </li>
      </ul>

      <p>We will respond to your inquiries as soon as possible.</p>

      <p>
        Please kindly note that this is a draft privacy policy and that you
        should consider consulting with a legal professional to ensure it meets
        the specific requirements of your app and complies with applicable laws
        and regulations.
      </p>
    </div>
  );
}
